### ISSUE TITLE
Interactive hist/KDEs

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#120]
https://plotly.com/python/distplot/

**Comment by jorgeboucas** [comment]
<img width="1192" alt="Screenshot 2020-08-10 at 13 27 24" src="https://user-images.githubusercontent.com/7725685/89778267-7dcf0b00-db0d-11ea-8e47-20bc9e60658d.png">

not working, example input here:

[violin plots test.xlsx](https://github.com/mpg-age-bioinformatics/flaski/files/5050551/violin.plots.test.xlsx)

**Comment by jorgeboucas** [comment]
<img width="1112" alt="Screenshot 2020-08-12 at 16 25 05" src="https://user-images.githubusercontent.com/7725685/90027172-8748a680-dcb8-11ea-8be7-99c1b1803a77.png">

failing when going on KDE

**Comment by jorgeboucas** [comment]
- [ ] it needs to be possible to do a KDE without the histogram
- [ ] KDE is failing if plotting 2 overlapping KDEs and Nans are in one of the datasets. ie. nans need to be removed for each independent KDE before plotting

**Comment by CamilaDuitama** [comment]
It is possible to plot a KDE without histogram if you untick the show histogram box
![Screenshot 2020-09-16 at 13 57 28](https://user-images.githubusercontent.com/33686652/93333169-32520000-f823-11ea-8be7-f21d23eec593.png)

**Comment by jorgeboucas** [comment]
- [ ] the option needs to be under Figure > Layout.
- [ ] notice that under a histogram and KDE we need to be able to see the settings for the histogram as well as for the KDE

**Comment by jorgeboucas** [comment]
issues with right axis in KDE: https://github.com/plotly/plotly.py/issues/1084#issuecomment-409191351
