### ISSUE TITLE
iCellplot new features

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#135]
- [x] change y-label
- [x] change font size of x label and y label
- [x] issues with white lines
- [x] include x-axis markers on top part of graph

**Comment by jorgeboucas** [comment]
not possible to remove minimal white lines, marker line width is already set to 0:

`fig.update_traces(marker_line_width=0)`

**Comment by jorgeboucas** [comment]
completed with version/tag 1.7.1

**Comment by FranziMe** [comment]
- [ ] reverse order of terms, i.e. what is on top in the excel file should be on top in the plot, right now it is bottom up
- [ ] option to write the number of genes per term next to the respective bar as in the original cell plots
- [ ] if possible take automatic scale limits and only change color; i.e. leave boxes for lower center upper - value empty, but still take the Color. right now, if you want custom colors you need to give lower, center, upper values
- [ ] if possible structure the options box a bit more intuitive for first time users

**Comment by jorgeboucas** [comment]
e22d16a
4c429f3
2663598

"structure (..) for first time users" will not be address here.
