### ISSUE TITLE
[FEATURE REQ.] GSEA plots

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#176]

**Comment by FranziMe** [comment]
TODOs:
- [ ]  label position
- [ ]  if label is given, subset label and ticks df to labeled positions
- [ ] remove groups
- [ ] clean up

**Comment by FranziMe** [comment]
The app is ready for testing

---

- [ ] tutorial video? (@jorgeboucas )

**Comment by jorgeboucas** [comment]
yes, tutorial video

also, 

- [ ] can @FranziMe put the demo data into `/utils/demo_data`

**Comment by FranziMe** [comment]
Tutorial:
https://datashare.mpcdf.mpg.de/s/CWhV6Ux93QADU9A

Let me know where I can deposit it

**Comment by jorgeboucas** [comment]
it's looking great I found 2 issues:
- [ ] add option rotation of labels (ie. angle)
- [ ] Axes > Ticks > lower :: Not removing the lower ticks; also not for the left ticks (this issue might already be on the iscatterplot -- needs checking).

**Comment by jorgeboucas** [comment]
- [ ] Axes > N ticks > X-axis not working

**Comment by jorgeboucas** [comment]
✅ in production
