### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#50]

**Comment by CamilaDuitama** [comment]
- [ ] Add customisable ticks and borders

**Comment by jorgeboucas** [comment]
- [ ] Arguments > Figure > Log Scale needs to go to  Arguments > Axis > Log Scale on the left side of "Line width"
- [ ] Arguments > Histogram x: all fields need to be inline (eg. not "Label" <value> in 2 different lines but in one single one.)
- [ ] spacing between  "DATA COLUMNS" and "ARGUMENTS" is too big and not in agreement with the other apps
- [ ] Arguments > Histogram x: Line width and fill alpha values need to be vertically centred and horizontally left aligned with 4 px left-padding.
- [ ] issue with figure title

<img width="739" alt="Screenshot 2020-06-16 at 18 26 54" src="https://user-images.githubusercontent.com/7725685/84801097-07c39180-afff-11ea-831e-247e188ffd92.png">

**Comment by jorgeboucas** [comment]
![ARGUMENTS](https://user-images.githubusercontent.com/7725685/85016456-0b275c00-b16a-11ea-8ed2-3ff61702988f.png)
![Title fontsize 14](https://user-images.githubusercontent.com/7725685/85016472-14182d80-b16a-11ea-8229-de71a3941353.png)
![Fill color None](https://user-images.githubusercontent.com/7725685/85016489-1aa6a500-b16a-11ea-86a3-e228a114852f.png)
![Fill color None](https://user-images.githubusercontent.com/7725685/85016799-bc2df680-b16a-11ea-8c7a-2d7813aae6c8.png)

**Comment by jorgeboucas** [comment]
arguments:
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html
density : bool, optional

**Comment by jorgeboucas** [comment]
![image](https://user-images.githubusercontent.com/7725685/85102620-53478c80-b205-11ea-8d88-024346882f93.png)
<img width="368" alt="Title Histogram" src="https://user-images.githubusercontent.com/7725685/85102646-60fd1200-b205-11ea-88b3-042df7b4eb95.png">
![IMG_E345EADD0E6D-1](https://user-images.githubusercontent.com/7725685/85102647-62c6d580-b205-11ea-9572-9704f153a582.jpeg)
![IMG_6D23DCEA9CAD-1](https://user-images.githubusercontent.com/7725685/85102650-62c6d580-b205-11ea-93ed-dd1449b95b3e.jpeg)
