### ISSUE TITLE
Circular bar plot

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#59]

**Comment by jorgeboucas** [comment]
Shiny eg. https://shiny.age.mpg.de/circbarplot/

**Comment by AIqbal94** [comment]
This is the one I got from the shiny app;
[circbarplot.xlsx](https://github.com/mpg-age-bioinformatics/flaski/files/6108601/circbarplot.xlsx)

**Comment by jorgeboucas** [comment]
- [ ] Angular Axis > Angular Tick Direction : outside, inside, none --- the none is missing although it is working

**Comment by jorgeboucas** [comment]
- [ ] improve defaults to look like the figure in this issue
- [ ] improve labels for bars so that they have the correct angle at their respective bar eg. 0 degrees when at 3 or 9 o'clock

[CircularBarPlot.pdf](https://github.com/mpg-age-bioinformatics/flaski/files/6109058/CircularBarPlot.pdf)

**Comment by jorgeboucas** [comment]
not possible to rotate the labels label-by-label

**Comment by jorgeboucas** [comment]
@AIqbal94 

can we not give a list of angles ?

what is the arg that leads to the rotation of the ticks label?

**Comment by AIqbal94** [comment]
@jorgeboucas 

Not quite sure which list of angles you mean

rotation of tick labels;
Angular Axis ---> Tick angle
