### ISSUE TITLE
Violin plots

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#60]

**Comment by jorgeboucas** [comment]
<img width="373" alt="o Figure" src="https://user-images.githubusercontent.com/7725685/85837129-f402f280-b797-11ea-976d-2e0b7538fb74.png">

<img width="373" alt="x label" src="https://user-images.githubusercontent.com/7725685/85837141-f9f8d380-b797-11ea-8fc2-3cdceb45f7d5.png">

<img width="373" alt="Arguments" src="https://user-images.githubusercontent.com/7725685/85837223-109f2a80-b798-11ea-94b1-462774831dee.png">

**Comment by jorgeboucas** [comment]
@CamilaDuitama I am not sure how the `hue` and `col` is being used / given in the UI.

**Comment by jorgeboucas** [comment]
what is "Data"

<img width="382" alt="image" src="https://user-images.githubusercontent.com/7725685/87152447-fc8a1b80-c2b5-11ea-983f-50addee93f0d.png">

**Comment by CamilaDuitama** [comment]
Data -> ["x, y, huenames of variables in data or vector data, optional. Inputs for plotting long-form data. See examples for interpretation"](https://seaborn.pydata.org/generated/seaborn.violinplot.html)

**Comment by jorgeboucas** [comment]
![image](https://user-images.githubusercontent.com/7725685/87782623-2f428f80-c833-11ea-90ac-a82776905be9.png)

- [ ] remove empty legend for simple violin plot without Hue

**Comment by CamilaDuitama** [comment]
- [ ] There is redundant information in the legend when there is more than one plot (e.g violin plot + swarm-lot)

**Comment by jorgeboucas** [comment]
<img width="1574" alt="Screenshot 2020-08-10 at 12 26 18" src="https://user-images.githubusercontent.com/7725685/89774416-1c576e00-db06-11ea-9bf6-b67281ca9287.png">

- [ ] remove the word "arguments" as this is already the arguments section
- [ ] allow inputting the different colours for each x value
- [ ] Add alpha to opacity

**Comment by CamilaDuitama** [comment]
Alpha is only a valid argument for swarmplot. Boxplot and Violinplot have the saturation argument instead (which is kind of similar).
I could also pass the option to matplotlib as said [here](https://github.com/mwaskom/seaborn/issues/979#issuecomment-235082271), but then then the alpha of the edges would change too. @jorgeboucas

**Comment by jorgeboucas** [comment]
<img width="1664" alt="Screenshot 2020-08-20 at 09 55 01" src="https://user-images.githubusercontent.com/7725685/90732353-4578bb00-e2cb-11ea-8561-60179845ac5e.png">

- [ ] issues with Hue=None

**Comment by jorgeboucas** [comment]
> In Seaborn, alpha is only a valid argument for swarmplot. Boxplot and Violinplot have the saturation argument instead (which is kind of similar).
> I could also pass the option to matplotlib as said [here](https://github.com/mwaskom/seaborn/issues/979#issuecomment-235082271), but then then the alpha of the edges would change too. @jorgeboucas

As we have different sub menus for Swarm, box, violin, you can implement saturation and alpha where it respectively applies

**Comment by jorgeboucas** [comment]
> * [ ]  There is redundant information in the legend when there is more than one plot (e.g violin plot + swarm-lot)

let's do it so that when a swarm plot is combined with another plot eg. violin plot only the legend for the swarm plot is displayed. this will allow to for example have a colour scheme for the violin plot while keeping the swarm plot markers all equal  (eg. black circles)
