### ISSUE TITLE
KEGG maps

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#93]

**Comment by chuangtsaide** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chuan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chuan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



COL11A1
MUC12
FRMD5
FCGBP
EGFL6
FN1
KLK5
ITGA9
WNT4
WNT2
WNT16
CXCL13
CBX8
S100A1
NDC80
NTM
RAB37
PPP1R14C
JAK3
EZH2
IGFBPL1
MTMR8
ATP5MC1P1
S100A4
HMX1

</body>

</html>
